name: Build
# Avoid triggering two build on PR
# https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2

      - name: Install, Build and Test 🔧
        run: |
          pnpm i
          pnpm -r build
